on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Run dependency diff action
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Downgrade dependency version to see the diff
        run: sed -i -E 's/androidx.paging:paging-common-ktx:[[:digit:]]+.[[:digit:]]+.[[:digit:]]+/androidx.paging:paging-common-ktx:3.2.0/g' testproject/build.gradle

      - uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: testproject
          arguments: dependencies
          gradle-home-cache-cleanup: true

      - id: dependency-diff
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          configuration: runtimeClasspath
          build-root-directory: testproject
          project: ""
          debug: true

      - uses: peter-evans/find-comment@v3
        id: find_comment
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Test1

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Test1
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  test-job-with-configuration-cache:
    runs-on: ubuntu-latest
    name: Test additional arguments
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Downgrade dependency version to see the diff
        run: sed -i -E 's/androidx.paging:paging-common-ktx:[[:digit:]]+.[[:digit:]]+.[[:digit:]]+/androidx.paging:paging-common-ktx:3.2.0/g' testproject/build.gradle

      - run: |
          mkdir -p ~/.gradle
          printf "org.gradle.unsafe.configuration-cache=true" > ~/.gradle/gradle.properties
        shell: bash

      - uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: testproject
          arguments: dependencies --no-configuration-cache
          gradle-home-cache-cleanup: true

      - id: dependency-diff
        uses: ./
        if: github.event_name == 'pull_request'
        with:
          configuration: runtimeClasspath
          lib-version: "1.2.1"
          build-root-directory: testproject
          additional-gradle-arguments: "--no-configuration-cache --stacktrace"
          project: ""

      - uses: peter-evans/find-comment@v3
        id: find_comment
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Test2

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Test2
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  test-on-different-os:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Execute on ${{ matrix.os }} runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Downgrade dependency version to see the diff
        run: sed -i -E 's/androidx.paging:paging-common-ktx:[[:digit:]]+.[[:digit:]]+.[[:digit:]]+/androidx.paging:paging-common-ktx:3.2.0/g' testproject/build.gradle

      - uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: testproject
          arguments: dependencies
          gradle-home-cache-cleanup: true

      - id: dependency-diff
        uses: ./
        if: github.event_name == 'pull_request'
        with:
          configuration: runtimeClasspath
          build-root-directory: testproject
          project: ""
          debug: true
          additional-gradle-arguments: "--scan"
